services:
  postgres:
    image: postgis/postgis:15-master
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - ./.data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
  api:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - postgres  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080